# alarm_cooldown_sec: 30
# alarm_http_token: ''
# alarm_transport: usb
# camera_feeds:
# - 0
# camera_titles:
# - Camera 1
# class_file: data/class_names.yaml
# confidence_threshold: 0.25
# esp_ip: ''
# gloves_model_path: weights/best.pt
# model_path: weights/helmet_model.pt
# mqtt_broker: ''
# mqtt_client_id: skycctv-ai
# mqtt_password: ''
# mqtt_port: 1883
# mqtt_qos: 1
# mqtt_retain: false
# mqtt_topic: skycctv/alarm
# mqtt_username: ''
# use_wifi: false



alarm_cooldown_sec: 30
alarm_http_token: ''
alarm_transport: usb
camera_feeds:
- rtsp://admin:admin%40123@192.168.20.103:554/cam/realmonitor?channel=27&subtype=0
- rtsp://admin:admin%40123@192.168.20.103:554/cam/realmonitor?channel=28&subtype=0
- rtsp://admin:admin%40123@192.168.20.103:554/cam/realmonitor?channel=29&subtype=0
camera_titles:
- Camera 1
- Camera 2
- Camera 4
class_file: data/class_names.yaml
confidence_threshold: 0.25
esp_ip: ''
gloves_model_path: weights/best.pt
model_path: weights/helmet_model.pt
mqtt_broker: ''
mqtt_client_id: skycctv-ai
mqtt_password: ''
mqtt_port: 1883
mqtt_qos: 1
mqtt_retain: false
mqtt_topic: skycctv/alarm
mqtt_username: ''
use_wifi: false
